# Generated by Django 5.2.8 on 2025-12-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
