# Generated by Django 6.0.6 on 2026-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_options_alter_payroll_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='net_salary_value',
            new_name='net_salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
