# Generated by Django 6.0.6 on 2026-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_attendance_is_half_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave')], default='PRESENT', max_length=20),
        ),
    ]
